exclude: ^(node_modules)/

repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
  hooks:
  - id: commitizen
    stages: [commit-msg]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-json
  - id: check-yaml
          ## Exclude all helm templates
    exclude: |
      (?x)^(
          .+/templates/.+\.yaml|
          \.gitlab-ci\.yml
      )$
  - id: check-merge-conflict

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-yaml
    fail_fast: true
    args: [--autofix, --indent, '2']
          ## Exclude all helm templates
    exclude: |
      (?x)^(
          .+/templates/.+\.yaml|
          \.gitlab-ci\.yml
      )$

- repo: local
  hooks:
  - id: js-eslint
    name: js-eslint
    entry: yarn lint
    language: system
    fail_fast: true
    pass_filenames: false
    types_or: [javascript, jsx, ts, tsx, json]

  - id: js-tsc-compile-check
    name: js-tsc-compile-check
    entry: yarn tsc-lint
    language: system
    fail_fast: true
    pass_filenames: false
    types_or: [javascript, jsx, ts, tsx, json]
