import classNames from 'classnames'
import '@styles/global.scss'
import type { Metadata } from 'next'
import { Source_Code_Pro, Source_Sans_3 } from 'next/font/google'

const sourceCodePro = Source_Code_Pro({
  subsets: ['latin'],
  preload: true,
  variable: '--font-family-sourceCodePro',
});

const sourceSansPro = Source_Sans_3({
  subsets: ['latin'],
  preload: true,
  variable: '--font-family-sourceSansPro',
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const fontClasses = classNames(
  sourceCodePro.className,
  sourceSansPro.className,
)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fontClasses}>{children}</body>
    </html>
  )
}
